//监听，当鼠标划上隐藏菜单栏消失
$(".subnavshow").mouseenter(function(){
    $("#sub-nav").show()
})
$(".subnavshow").mouseleave(function(){
    $("#sub-nav").hide()
})
$(".subnavshow").mouseenter(function(){
    $("#sub-nav").show()
})
$(".subnavshow").mouseleave(function(){
    $("#sub-nav").hide()
})